################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# Main Monitor (HDMI-A-1)
monitor=HDMI-A-1, 1920x1200@60, 0x0, 1

# Second Monitor (DVI-D-2) - Positioned to the right
monitor=DVI-D-2, 1920x1080@50, 1920x0, 1
